### ISSUE TITLE
Circle Ci nose test failure (closestPoints)

### ISSUE THREAD

**Issue by markus-stoll** [CognitionGuidedSurgery/msml#204]
ERROR: test_closestPoints_with_radius (msmltest.OperatorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/msml/src/msmltest/operators.py", line 94, in test_closestPoints_with_radius
    result = vtk.closest_point(input_file, vector=(0.0, 0.0, 0.0), radius=10.0)
  File "/home/ubuntu/msml/src/msml/ext/msmlvtk.py", line 106, in closest_point
    locator = vtk.vtkPointLocator()
NameError: global name 'vtk' is not defined

**Comment by markus-stoll** [comment]
same error again!?

https://circleci.com/gh/CognitionGuidedSurgery/msml/398
```
test_closestPoints_with_radius (msmltest.OperatorTest) ... share/run_test.sh: line 14: 26084 Segmentation fault      (core dumped) nosetests -vv --with-coverage --cover-tests --cover-inclusive --cover-package=msml --cover-erase -w src msmltest
```

**Comment by dschauba** [comment]
Yeah ;(

**Comment by areku** [comment]
@dschauba is python-vtk in the PYTHONPATH?

I have worked on it over christmas.  VTK6.1 got a installation folder.  The problem is, that every little mistake, like missing files, leads to VTK segfault. 

I have put it on my [TODOs](https://github.com/CognitionGuidedSurgery/msml/wiki/weigl%27s-notebook#todos), but I cannot say, whether this get fixed until the end of my contract.

So long you can comment both test cases out.

**Comment by dschauba** [comment]
Yeah, thanks, forgot that, of course.
