### ISSUE TITLE
generate CLI for mitral valve example

### ISSUE THREAD

**Issue by markus-stoll** [CognitionGuidedSurgery/msml#217]
0. Which parameters are important?
1. Pack example into single .py script (see msml/examples/PythonExamples/Beam/runner_test.py
)
2. the script must return a cli xml description of its input/output.

**Comment by areku** [comment]
We have already support for this with `https://github.com/CognitionGuidedSurgery/msml/blob/experimental/src/msml/api/clisupport.py`.

There are still some problems: 

* rdflib create output over the `logging` api, this corrupts the xml
* There is no knowledge about output/return value of a workflow.
* How does CLI handles output values?

Nevertheless, following should work 

```
from msml.api.clisupport import * 
MSMLFILE = '/homes/students/weigl/workspace1/msml/examples/BunnyExample/bunny.msml.xml'                                             
if __name__ == "__main__": 
  cli_app(MSMLFILE)
```

**Comment by markus-stoll** [comment]
Sound good, maybe can can makle the next step an call a MSML workflow (e.g. mitral valve example)  from a CLI platform e.g. MITK?

**Comment by markus-stoll** [comment]
Current state: 
CLI scripst can be genrated and integrated into MITK using the . Handling of our data formats (inout parameter/output to MITK datatree) is in discussion.

Usage example:
`pip install pyclictk`
`..\..\src\msml.py cli beamLinearDisp.msml.xml -e nsofa`
`beamLinearDisp.msml.py`

You need to add `role="Input"` for all vars that should be used as input!

**Comment by NicolaiSchoch** [comment]
Also, you need to add `role="fix"` for all other variables.

**Comment by NicolaiSchoch** [comment]
Finally, the workflow for generating and then executing a CLI script should be as follows:

1.) Test pipeline execution
`python ../../src/msml.py exec bunnyCGAL_HiFlow3.msml.xml -e hiflow3`

2.) Generate CLI script via
`python ../../src/msml.py cli bunnyCGAL_HiFlow3.msml.xml -e hiflow3`
This produces the file ``bunnyCGAL_HiFlow3.msml.py`

3.) Check out the CLI xml file via
`python bunnyCGAL_HiFlow3.msml.py --xml > bunnyCGAL_HiFlow3.msml.py.CLIinfo.xml`
in order to figure out how to use the variables as parameters for the CLI execution.
E.g. here, the "name" of the input variable is `input_surf_mesh`

4.) Execute CLI script via
`python bunnyCGAL_HiFlow3.msml.py --input_surf_mesh Bunny6000Surface.vtk`
possibly direct simulation output from console into `history.txt` file via
`python bunnyCGAL_HiFlow3.msml.py --input_surf_mesh Bunny6000Surface.vtk > history.txt`

---

What still doesn't work, is the `--help` or `-h` option... these don't produce anything... do they?
I cannot find any implementation of this functionality either... as opposed to the `--xml` option, which is in `src/msml/api/clisupport.py`.
However, they somehow should, as mentioned in areku's post on 11 Feb in https://github.com/CognitionGuidedSurgery/msml/issues/217.
Then, one could omit step 3) in the above description, and directly know how to handle step 4).

Any ideas how to get the `--help` work?
